/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFacultyRouteImport } from './routes/_authenticated/faculty'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgramsRouteImport } from './routes/_authenticated/programs'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedTeachingRouteImport } from './routes/_authenticated/teaching'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedAcademicsIndexRouteImport } from './routes/_authenticated/academics/index'
import { Route as AuthenticatedAcademicsAllocationsRouteImport } from './routes/_authenticated/academics/allocations'
import { Route as AuthenticatedAcademicsAnalyticsRouteImport } from './routes/_authenticated/academics/analytics'
import { Route as AuthenticatedAcademicsBulkRouteImport } from './routes/_authenticated/academics/bulk'
import { Route as AuthenticatedAcademicsCalendarRouteImport } from './routes/_authenticated/academics/calendar'
import { Route as AuthenticatedAcademicsCreditsRouteImport } from './routes/_authenticated/academics/credits'
import { Route as AuthenticatedAcademicsCurriculumRouteImport } from './routes/_authenticated/academics/curriculum'
import { Route as AuthenticatedAcademicsEnrollmentRouteImport } from './routes/_authenticated/academics/enrollment'
import { Route as AuthenticatedAcademicsInfrastructureRouteImport } from './routes/_authenticated/academics/infrastructure'
import { Route as AuthenticatedAcademicsReportsRouteImport } from './routes/_authenticated/academics/reports'
import { Route as AuthenticatedAcademicsStructureRouteImport } from './routes/_authenticated/academics/structure'
import { Route as AuthenticatedAcademicsSubjectsRouteImport } from './routes/_authenticated/academics/subjects'
import { Route as AuthenticatedAcademicsWorkloadRouteImport } from './routes/_authenticated/academics/workload'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAttendanceAnalyticsRouteImport } from './routes/_authenticated/attendance/analytics'
import { Route as AuthenticatedAttendanceCorrectionsRouteImport } from './routes/_authenticated/attendance/corrections'
import { Route as AuthenticatedAttendanceLeaveRouteImport } from './routes/_authenticated/attendance/leave'
import { Route as AuthenticatedAttendanceMarkRouteImport } from './routes/_authenticated/attendance/mark'
import { Route as AuthenticatedAttendanceMyRouteImport } from './routes/_authenticated/attendance/my'
import { Route as AuthenticatedAttendancePoliciesRouteImport } from './routes/_authenticated/attendance/policies'
import { Route as AuthenticatedAttendanceReportsRouteImport } from './routes/_authenticated/attendance/reports'
import { Route as AuthenticatedAttendanceSessionsRouteImport } from './routes/_authenticated/attendance/sessions'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedExamsAnalyticsRouteImport } from './routes/_authenticated/exams/analytics'
import { Route as AuthenticatedExamsCertificatesRouteImport } from './routes/_authenticated/exams/certificates'
import { Route as AuthenticatedExamsEvaluationRouteImport } from './routes/_authenticated/exams/evaluation'
import { Route as AuthenticatedExamsFrameworkRouteImport } from './routes/_authenticated/exams/framework'
import { Route as AuthenticatedExamsHallTicketsRouteImport } from './routes/_authenticated/exams/hall-tickets'
import { Route as AuthenticatedExamsInvigilationRouteImport } from './routes/_authenticated/exams/invigilation'
import { Route as AuthenticatedExamsMarksRouteImport } from './routes/_authenticated/exams/marks'
import { Route as AuthenticatedExamsPapersRouteImport } from './routes/_authenticated/exams/papers'
import { Route as AuthenticatedExamsPlanningRouteImport } from './routes/_authenticated/exams/planning'
import { Route as AuthenticatedExamsQuestionBankRouteImport } from './routes/_authenticated/exams/question-bank'
import { Route as AuthenticatedExamsRegistrationsRouteImport } from './routes/_authenticated/exams/registrations'
import { Route as AuthenticatedExamsReportsRouteImport } from './routes/_authenticated/exams/reports'
import { Route as AuthenticatedExamsResultsRouteImport } from './routes/_authenticated/exams/results'
import { Route as AuthenticatedExamsRevaluationRouteImport } from './routes/_authenticated/exams/revaluation'
import { Route as AuthenticatedExamsSeatingRouteImport } from './routes/_authenticated/exams/seating'
import { Route as AuthenticatedExamsSessionsRouteImport } from './routes/_authenticated/exams/sessions'
import { Route as AuthenticatedLmsIndexRouteImport } from './routes/_authenticated/lms/index'
import { Route as AuthenticatedLmsWorkspaceIdRouteImport } from './routes/_authenticated/lms/$workspaceId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsScopeRouteImport } from './routes/_authenticated/settings/$scope'
import { Route as AuthenticatedSettingsApiRouteImport } from './routes/_authenticated/settings/api'
import { Route as AuthenticatedSettingsFeaturesRouteImport } from './routes/_authenticated/settings/features'
import { Route as AuthenticatedSettingsStorageRouteImport } from './routes/_authenticated/settings/storage'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students/$studentId'
import { Route as AuthenticatedStudentsAdmissionsRouteImport } from './routes/_authenticated/students/admissions'
import { Route as AuthenticatedStudentsIdCardsRouteImport } from './routes/_authenticated/students/id-cards'
import { Route as AuthenticatedStudentsImportRouteImport } from './routes/_authenticated/students/import'
import { Route as AuthenticatedStudentsReportsRouteImport } from './routes/_authenticated/students/reports'
import { Route as AuthenticatedTimetableIndexRouteImport } from './routes/_authenticated/timetable/index'
import { Route as AuthenticatedTimetableSubstitutionsRouteImport } from './routes/_authenticated/timetable/substitutions'
import { Route as ApiPublicVerifyRouteImport } from './routes/api/public/verify'
import { Route as AuthenticatedAcademicsDepartmentsDepartmentIdRouteImport } from './routes/_authenticated/academics/departments.$departmentId'
import { Route as AuthenticatedAcademicsProgramsProgramIdRouteImport } from './routes/_authenticated/academics/programs.$programId'
import { Route as AuthenticatedSettingsTemplatesChannelRouteImport } from './routes/_authenticated/settings/templates.$channel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacultyRoute = AuthenticatedFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramsRoute = AuthenticatedProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachingRoute = AuthenticatedTeachingRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicsIndexRoute =
  AuthenticatedAcademicsIndexRouteImport.update({
    id: '/academics/',
    path: '/academics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsAllocationsRoute =
  AuthenticatedAcademicsAllocationsRouteImport.update({
    id: '/academics/allocations',
    path: '/academics/allocations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsAnalyticsRoute =
  AuthenticatedAcademicsAnalyticsRouteImport.update({
    id: '/academics/analytics',
    path: '/academics/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsBulkRoute =
  AuthenticatedAcademicsBulkRouteImport.update({
    id: '/academics/bulk',
    path: '/academics/bulk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsCalendarRoute =
  AuthenticatedAcademicsCalendarRouteImport.update({
    id: '/academics/calendar',
    path: '/academics/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsCreditsRoute =
  AuthenticatedAcademicsCreditsRouteImport.update({
    id: '/academics/credits',
    path: '/academics/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsCurriculumRoute =
  AuthenticatedAcademicsCurriculumRouteImport.update({
    id: '/academics/curriculum',
    path: '/academics/curriculum',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsEnrollmentRoute =
  AuthenticatedAcademicsEnrollmentRouteImport.update({
    id: '/academics/enrollment',
    path: '/academics/enrollment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsInfrastructureRoute =
  AuthenticatedAcademicsInfrastructureRouteImport.update({
    id: '/academics/infrastructure',
    path: '/academics/infrastructure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsReportsRoute =
  AuthenticatedAcademicsReportsRouteImport.update({
    id: '/academics/reports',
    path: '/academics/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsStructureRoute =
  AuthenticatedAcademicsStructureRouteImport.update({
    id: '/academics/structure',
    path: '/academics/structure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsSubjectsRoute =
  AuthenticatedAcademicsSubjectsRouteImport.update({
    id: '/academics/subjects',
    path: '/academics/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsWorkloadRoute =
  AuthenticatedAcademicsWorkloadRouteImport.update({
    id: '/academics/workload',
    path: '/academics/workload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceAnalyticsRoute =
  AuthenticatedAttendanceAnalyticsRouteImport.update({
    id: '/attendance/analytics',
    path: '/attendance/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceCorrectionsRoute =
  AuthenticatedAttendanceCorrectionsRouteImport.update({
    id: '/attendance/corrections',
    path: '/attendance/corrections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceLeaveRoute =
  AuthenticatedAttendanceLeaveRouteImport.update({
    id: '/attendance/leave',
    path: '/attendance/leave',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMarkRoute =
  AuthenticatedAttendanceMarkRouteImport.update({
    id: '/attendance/mark',
    path: '/attendance/mark',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMyRoute =
  AuthenticatedAttendanceMyRouteImport.update({
    id: '/attendance/my',
    path: '/attendance/my',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendancePoliciesRoute =
  AuthenticatedAttendancePoliciesRouteImport.update({
    id: '/attendance/policies',
    path: '/attendance/policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceReportsRoute =
  AuthenticatedAttendanceReportsRouteImport.update({
    id: '/attendance/reports',
    path: '/attendance/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceSessionsRoute =
  AuthenticatedAttendanceSessionsRouteImport.update({
    id: '/attendance/sessions',
    path: '/attendance/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsAnalyticsRoute =
  AuthenticatedExamsAnalyticsRouteImport.update({
    id: '/exams/analytics',
    path: '/exams/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsCertificatesRoute =
  AuthenticatedExamsCertificatesRouteImport.update({
    id: '/exams/certificates',
    path: '/exams/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsEvaluationRoute =
  AuthenticatedExamsEvaluationRouteImport.update({
    id: '/exams/evaluation',
    path: '/exams/evaluation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsFrameworkRoute =
  AuthenticatedExamsFrameworkRouteImport.update({
    id: '/exams/framework',
    path: '/exams/framework',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsHallTicketsRoute =
  AuthenticatedExamsHallTicketsRouteImport.update({
    id: '/exams/hall-tickets',
    path: '/exams/hall-tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsInvigilationRoute =
  AuthenticatedExamsInvigilationRouteImport.update({
    id: '/exams/invigilation',
    path: '/exams/invigilation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsMarksRoute = AuthenticatedExamsMarksRouteImport.update({
  id: '/exams/marks',
  path: '/exams/marks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsPapersRoute =
  AuthenticatedExamsPapersRouteImport.update({
    id: '/exams/papers',
    path: '/exams/papers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsPlanningRoute =
  AuthenticatedExamsPlanningRouteImport.update({
    id: '/exams/planning',
    path: '/exams/planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsQuestionBankRoute =
  AuthenticatedExamsQuestionBankRouteImport.update({
    id: '/exams/question-bank',
    path: '/exams/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsRegistrationsRoute =
  AuthenticatedExamsRegistrationsRouteImport.update({
    id: '/exams/registrations',
    path: '/exams/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsReportsRoute =
  AuthenticatedExamsReportsRouteImport.update({
    id: '/exams/reports',
    path: '/exams/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsResultsRoute =
  AuthenticatedExamsResultsRouteImport.update({
    id: '/exams/results',
    path: '/exams/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsRevaluationRoute =
  AuthenticatedExamsRevaluationRouteImport.update({
    id: '/exams/revaluation',
    path: '/exams/revaluation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsSeatingRoute =
  AuthenticatedExamsSeatingRouteImport.update({
    id: '/exams/seating',
    path: '/exams/seating',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsSessionsRoute =
  AuthenticatedExamsSessionsRouteImport.update({
    id: '/exams/sessions',
    path: '/exams/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLmsIndexRoute = AuthenticatedLmsIndexRouteImport.update({
  id: '/lms/',
  path: '/lms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLmsWorkspaceIdRoute =
  AuthenticatedLmsWorkspaceIdRouteImport.update({
    id: '/lms/$workspaceId',
    path: '/lms/$workspaceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsScopeRoute =
  AuthenticatedSettingsScopeRouteImport.update({
    id: '/$scope',
    path: '/$scope',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiRoute =
  AuthenticatedSettingsApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsFeaturesRoute =
  AuthenticatedSettingsFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsStorageRoute =
  AuthenticatedSettingsStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsAdmissionsRoute =
  AuthenticatedStudentsAdmissionsRouteImport.update({
    id: '/students/admissions',
    path: '/students/admissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIdCardsRoute =
  AuthenticatedStudentsIdCardsRouteImport.update({
    id: '/students/id-cards',
    path: '/students/id-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsImportRoute =
  AuthenticatedStudentsImportRouteImport.update({
    id: '/students/import',
    path: '/students/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsReportsRoute =
  AuthenticatedStudentsReportsRouteImport.update({
    id: '/students/reports',
    path: '/students/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableIndexRoute =
  AuthenticatedTimetableIndexRouteImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimetableSubstitutionsRoute =
  AuthenticatedTimetableSubstitutionsRouteImport.update({
    id: '/timetable/substitutions',
    path: '/timetable/substitutions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicVerifyRoute = ApiPublicVerifyRouteImport.update({
  id: '/api/public/verify',
  path: '/api/public/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademicsDepartmentsDepartmentIdRoute =
  AuthenticatedAcademicsDepartmentsDepartmentIdRouteImport.update({
    id: '/academics/departments/$departmentId',
    path: '/academics/departments/$departmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicsProgramsProgramIdRoute =
  AuthenticatedAcademicsProgramsProgramIdRouteImport.update({
    id: '/academics/programs/$programId',
    path: '/academics/programs/$programId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTemplatesChannelRoute =
  AuthenticatedSettingsTemplatesChannelRouteImport.update({
    id: '/templates/$channel',
    path: '/templates/$channel',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/faculty': typeof AuthenticatedFacultyRoute
  '/media': typeof AuthenticatedMediaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/student': typeof AuthenticatedStudentRoute
  '/teaching': typeof AuthenticatedTeachingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/academics/allocations': typeof AuthenticatedAcademicsAllocationsRoute
  '/academics/analytics': typeof AuthenticatedAcademicsAnalyticsRoute
  '/academics/bulk': typeof AuthenticatedAcademicsBulkRoute
  '/academics/calendar': typeof AuthenticatedAcademicsCalendarRoute
  '/academics/credits': typeof AuthenticatedAcademicsCreditsRoute
  '/academics/curriculum': typeof AuthenticatedAcademicsCurriculumRoute
  '/academics/enrollment': typeof AuthenticatedAcademicsEnrollmentRoute
  '/academics/infrastructure': typeof AuthenticatedAcademicsInfrastructureRoute
  '/academics/reports': typeof AuthenticatedAcademicsReportsRoute
  '/academics/structure': typeof AuthenticatedAcademicsStructureRoute
  '/academics/subjects': typeof AuthenticatedAcademicsSubjectsRoute
  '/academics/workload': typeof AuthenticatedAcademicsWorkloadRoute
  '/attendance/analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/attendance/corrections': typeof AuthenticatedAttendanceCorrectionsRoute
  '/attendance/leave': typeof AuthenticatedAttendanceLeaveRoute
  '/attendance/mark': typeof AuthenticatedAttendanceMarkRoute
  '/attendance/my': typeof AuthenticatedAttendanceMyRoute
  '/attendance/policies': typeof AuthenticatedAttendancePoliciesRoute
  '/attendance/reports': typeof AuthenticatedAttendanceReportsRoute
  '/attendance/sessions': typeof AuthenticatedAttendanceSessionsRoute
  '/exams/analytics': typeof AuthenticatedExamsAnalyticsRoute
  '/exams/certificates': typeof AuthenticatedExamsCertificatesRoute
  '/exams/evaluation': typeof AuthenticatedExamsEvaluationRoute
  '/exams/framework': typeof AuthenticatedExamsFrameworkRoute
  '/exams/hall-tickets': typeof AuthenticatedExamsHallTicketsRoute
  '/exams/invigilation': typeof AuthenticatedExamsInvigilationRoute
  '/exams/marks': typeof AuthenticatedExamsMarksRoute
  '/exams/papers': typeof AuthenticatedExamsPapersRoute
  '/exams/planning': typeof AuthenticatedExamsPlanningRoute
  '/exams/question-bank': typeof AuthenticatedExamsQuestionBankRoute
  '/exams/registrations': typeof AuthenticatedExamsRegistrationsRoute
  '/exams/reports': typeof AuthenticatedExamsReportsRoute
  '/exams/results': typeof AuthenticatedExamsResultsRoute
  '/exams/revaluation': typeof AuthenticatedExamsRevaluationRoute
  '/exams/seating': typeof AuthenticatedExamsSeatingRoute
  '/exams/sessions': typeof AuthenticatedExamsSessionsRoute
  '/lms/$workspaceId': typeof AuthenticatedLmsWorkspaceIdRoute
  '/settings/$scope': typeof AuthenticatedSettingsScopeRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/features': typeof AuthenticatedSettingsFeaturesRoute
  '/settings/storage': typeof AuthenticatedSettingsStorageRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/admissions': typeof AuthenticatedStudentsAdmissionsRoute
  '/students/id-cards': typeof AuthenticatedStudentsIdCardsRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/students/reports': typeof AuthenticatedStudentsReportsRoute
  '/timetable/substitutions': typeof AuthenticatedTimetableSubstitutionsRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/academics/': typeof AuthenticatedAcademicsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/lms/': typeof AuthenticatedLmsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/academics/departments/$departmentId': typeof AuthenticatedAcademicsDepartmentsDepartmentIdRoute
  '/academics/programs/$programId': typeof AuthenticatedAcademicsProgramsProgramIdRoute
  '/settings/templates/$channel': typeof AuthenticatedSettingsTemplatesChannelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/faculty': typeof AuthenticatedFacultyRoute
  '/media': typeof AuthenticatedMediaRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programs': typeof AuthenticatedProgramsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/student': typeof AuthenticatedStudentRoute
  '/teaching': typeof AuthenticatedTeachingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/academics/allocations': typeof AuthenticatedAcademicsAllocationsRoute
  '/academics/analytics': typeof AuthenticatedAcademicsAnalyticsRoute
  '/academics/bulk': typeof AuthenticatedAcademicsBulkRoute
  '/academics/calendar': typeof AuthenticatedAcademicsCalendarRoute
  '/academics/credits': typeof AuthenticatedAcademicsCreditsRoute
  '/academics/curriculum': typeof AuthenticatedAcademicsCurriculumRoute
  '/academics/enrollment': typeof AuthenticatedAcademicsEnrollmentRoute
  '/academics/infrastructure': typeof AuthenticatedAcademicsInfrastructureRoute
  '/academics/reports': typeof AuthenticatedAcademicsReportsRoute
  '/academics/structure': typeof AuthenticatedAcademicsStructureRoute
  '/academics/subjects': typeof AuthenticatedAcademicsSubjectsRoute
  '/academics/workload': typeof AuthenticatedAcademicsWorkloadRoute
  '/attendance/analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/attendance/corrections': typeof AuthenticatedAttendanceCorrectionsRoute
  '/attendance/leave': typeof AuthenticatedAttendanceLeaveRoute
  '/attendance/mark': typeof AuthenticatedAttendanceMarkRoute
  '/attendance/my': typeof AuthenticatedAttendanceMyRoute
  '/attendance/policies': typeof AuthenticatedAttendancePoliciesRoute
  '/attendance/reports': typeof AuthenticatedAttendanceReportsRoute
  '/attendance/sessions': typeof AuthenticatedAttendanceSessionsRoute
  '/exams/analytics': typeof AuthenticatedExamsAnalyticsRoute
  '/exams/certificates': typeof AuthenticatedExamsCertificatesRoute
  '/exams/evaluation': typeof AuthenticatedExamsEvaluationRoute
  '/exams/framework': typeof AuthenticatedExamsFrameworkRoute
  '/exams/hall-tickets': typeof AuthenticatedExamsHallTicketsRoute
  '/exams/invigilation': typeof AuthenticatedExamsInvigilationRoute
  '/exams/marks': typeof AuthenticatedExamsMarksRoute
  '/exams/papers': typeof AuthenticatedExamsPapersRoute
  '/exams/planning': typeof AuthenticatedExamsPlanningRoute
  '/exams/question-bank': typeof AuthenticatedExamsQuestionBankRoute
  '/exams/registrations': typeof AuthenticatedExamsRegistrationsRoute
  '/exams/reports': typeof AuthenticatedExamsReportsRoute
  '/exams/results': typeof AuthenticatedExamsResultsRoute
  '/exams/revaluation': typeof AuthenticatedExamsRevaluationRoute
  '/exams/seating': typeof AuthenticatedExamsSeatingRoute
  '/exams/sessions': typeof AuthenticatedExamsSessionsRoute
  '/lms/$workspaceId': typeof AuthenticatedLmsWorkspaceIdRoute
  '/settings/$scope': typeof AuthenticatedSettingsScopeRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/features': typeof AuthenticatedSettingsFeaturesRoute
  '/settings/storage': typeof AuthenticatedSettingsStorageRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/admissions': typeof AuthenticatedStudentsAdmissionsRoute
  '/students/id-cards': typeof AuthenticatedStudentsIdCardsRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/students/reports': typeof AuthenticatedStudentsReportsRoute
  '/timetable/substitutions': typeof AuthenticatedTimetableSubstitutionsRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/academics': typeof AuthenticatedAcademicsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/lms': typeof AuthenticatedLmsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/timetable': typeof AuthenticatedTimetableIndexRoute
  '/academics/departments/$departmentId': typeof AuthenticatedAcademicsDepartmentsDepartmentIdRoute
  '/academics/programs/$programId': typeof AuthenticatedAcademicsProgramsProgramIdRoute
  '/settings/templates/$channel': typeof AuthenticatedSettingsTemplatesChannelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forbidden': typeof ForbiddenRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/faculty': typeof AuthenticatedFacultyRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programs': typeof AuthenticatedProgramsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/teaching': typeof AuthenticatedTeachingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/academics/allocations': typeof AuthenticatedAcademicsAllocationsRoute
  '/_authenticated/academics/analytics': typeof AuthenticatedAcademicsAnalyticsRoute
  '/_authenticated/academics/bulk': typeof AuthenticatedAcademicsBulkRoute
  '/_authenticated/academics/calendar': typeof AuthenticatedAcademicsCalendarRoute
  '/_authenticated/academics/credits': typeof AuthenticatedAcademicsCreditsRoute
  '/_authenticated/academics/curriculum': typeof AuthenticatedAcademicsCurriculumRoute
  '/_authenticated/academics/enrollment': typeof AuthenticatedAcademicsEnrollmentRoute
  '/_authenticated/academics/infrastructure': typeof AuthenticatedAcademicsInfrastructureRoute
  '/_authenticated/academics/reports': typeof AuthenticatedAcademicsReportsRoute
  '/_authenticated/academics/structure': typeof AuthenticatedAcademicsStructureRoute
  '/_authenticated/academics/subjects': typeof AuthenticatedAcademicsSubjectsRoute
  '/_authenticated/academics/workload': typeof AuthenticatedAcademicsWorkloadRoute
  '/_authenticated/attendance/analytics': typeof AuthenticatedAttendanceAnalyticsRoute
  '/_authenticated/attendance/corrections': typeof AuthenticatedAttendanceCorrectionsRoute
  '/_authenticated/attendance/leave': typeof AuthenticatedAttendanceLeaveRoute
  '/_authenticated/attendance/mark': typeof AuthenticatedAttendanceMarkRoute
  '/_authenticated/attendance/my': typeof AuthenticatedAttendanceMyRoute
  '/_authenticated/attendance/policies': typeof AuthenticatedAttendancePoliciesRoute
  '/_authenticated/attendance/reports': typeof AuthenticatedAttendanceReportsRoute
  '/_authenticated/attendance/sessions': typeof AuthenticatedAttendanceSessionsRoute
  '/_authenticated/exams/analytics': typeof AuthenticatedExamsAnalyticsRoute
  '/_authenticated/exams/certificates': typeof AuthenticatedExamsCertificatesRoute
  '/_authenticated/exams/evaluation': typeof AuthenticatedExamsEvaluationRoute
  '/_authenticated/exams/framework': typeof AuthenticatedExamsFrameworkRoute
  '/_authenticated/exams/hall-tickets': typeof AuthenticatedExamsHallTicketsRoute
  '/_authenticated/exams/invigilation': typeof AuthenticatedExamsInvigilationRoute
  '/_authenticated/exams/marks': typeof AuthenticatedExamsMarksRoute
  '/_authenticated/exams/papers': typeof AuthenticatedExamsPapersRoute
  '/_authenticated/exams/planning': typeof AuthenticatedExamsPlanningRoute
  '/_authenticated/exams/question-bank': typeof AuthenticatedExamsQuestionBankRoute
  '/_authenticated/exams/registrations': typeof AuthenticatedExamsRegistrationsRoute
  '/_authenticated/exams/reports': typeof AuthenticatedExamsReportsRoute
  '/_authenticated/exams/results': typeof AuthenticatedExamsResultsRoute
  '/_authenticated/exams/revaluation': typeof AuthenticatedExamsRevaluationRoute
  '/_authenticated/exams/seating': typeof AuthenticatedExamsSeatingRoute
  '/_authenticated/exams/sessions': typeof AuthenticatedExamsSessionsRoute
  '/_authenticated/lms/$workspaceId': typeof AuthenticatedLmsWorkspaceIdRoute
  '/_authenticated/settings/$scope': typeof AuthenticatedSettingsScopeRoute
  '/_authenticated/settings/api': typeof AuthenticatedSettingsApiRoute
  '/_authenticated/settings/features': typeof AuthenticatedSettingsFeaturesRoute
  '/_authenticated/settings/storage': typeof AuthenticatedSettingsStorageRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/students/admissions': typeof AuthenticatedStudentsAdmissionsRoute
  '/_authenticated/students/id-cards': typeof AuthenticatedStudentsIdCardsRoute
  '/_authenticated/students/import': typeof AuthenticatedStudentsImportRoute
  '/_authenticated/students/reports': typeof AuthenticatedStudentsReportsRoute
  '/_authenticated/timetable/substitutions': typeof AuthenticatedTimetableSubstitutionsRoute
  '/api/public/verify': typeof ApiPublicVerifyRoute
  '/_authenticated/academics/': typeof AuthenticatedAcademicsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/lms/': typeof AuthenticatedLmsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/timetable/': typeof AuthenticatedTimetableIndexRoute
  '/_authenticated/academics/departments/$departmentId': typeof AuthenticatedAcademicsDepartmentsDepartmentIdRoute
  '/_authenticated/academics/programs/$programId': typeof AuthenticatedAcademicsProgramsProgramIdRoute
  '/_authenticated/settings/templates/$channel': typeof AuthenticatedSettingsTemplatesChannelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forbidden'
    | '/maintenance'
    | '/reset-password'
    | '/unauthorized'
    | '/verify'
    | '/settings'
    | '/activity'
    | '/approvals'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/faculty'
    | '/media'
    | '/notifications'
    | '/profile'
    | '/programs'
    | '/roles'
    | '/staff'
    | '/student'
    | '/teaching'
    | '/users'
    | '/academics/allocations'
    | '/academics/analytics'
    | '/academics/bulk'
    | '/academics/calendar'
    | '/academics/credits'
    | '/academics/curriculum'
    | '/academics/enrollment'
    | '/academics/infrastructure'
    | '/academics/reports'
    | '/academics/structure'
    | '/academics/subjects'
    | '/academics/workload'
    | '/attendance/analytics'
    | '/attendance/corrections'
    | '/attendance/leave'
    | '/attendance/mark'
    | '/attendance/my'
    | '/attendance/policies'
    | '/attendance/reports'
    | '/attendance/sessions'
    | '/exams/analytics'
    | '/exams/certificates'
    | '/exams/evaluation'
    | '/exams/framework'
    | '/exams/hall-tickets'
    | '/exams/invigilation'
    | '/exams/marks'
    | '/exams/papers'
    | '/exams/planning'
    | '/exams/question-bank'
    | '/exams/registrations'
    | '/exams/reports'
    | '/exams/results'
    | '/exams/revaluation'
    | '/exams/seating'
    | '/exams/sessions'
    | '/lms/$workspaceId'
    | '/settings/$scope'
    | '/settings/api'
    | '/settings/features'
    | '/settings/storage'
    | '/students/$studentId'
    | '/students/admissions'
    | '/students/id-cards'
    | '/students/import'
    | '/students/reports'
    | '/timetable/substitutions'
    | '/api/public/verify'
    | '/academics/'
    | '/attendance/'
    | '/exams/'
    | '/lms/'
    | '/settings/'
    | '/students/'
    | '/timetable/'
    | '/academics/departments/$departmentId'
    | '/academics/programs/$programId'
    | '/settings/templates/$channel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forbidden'
    | '/maintenance'
    | '/reset-password'
    | '/unauthorized'
    | '/verify'
    | '/activity'
    | '/approvals'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/documents'
    | '/faculty'
    | '/media'
    | '/notifications'
    | '/profile'
    | '/programs'
    | '/roles'
    | '/staff'
    | '/student'
    | '/teaching'
    | '/users'
    | '/academics/allocations'
    | '/academics/analytics'
    | '/academics/bulk'
    | '/academics/calendar'
    | '/academics/credits'
    | '/academics/curriculum'
    | '/academics/enrollment'
    | '/academics/infrastructure'
    | '/academics/reports'
    | '/academics/structure'
    | '/academics/subjects'
    | '/academics/workload'
    | '/attendance/analytics'
    | '/attendance/corrections'
    | '/attendance/leave'
    | '/attendance/mark'
    | '/attendance/my'
    | '/attendance/policies'
    | '/attendance/reports'
    | '/attendance/sessions'
    | '/exams/analytics'
    | '/exams/certificates'
    | '/exams/evaluation'
    | '/exams/framework'
    | '/exams/hall-tickets'
    | '/exams/invigilation'
    | '/exams/marks'
    | '/exams/papers'
    | '/exams/planning'
    | '/exams/question-bank'
    | '/exams/registrations'
    | '/exams/reports'
    | '/exams/results'
    | '/exams/revaluation'
    | '/exams/seating'
    | '/exams/sessions'
    | '/lms/$workspaceId'
    | '/settings/$scope'
    | '/settings/api'
    | '/settings/features'
    | '/settings/storage'
    | '/students/$studentId'
    | '/students/admissions'
    | '/students/id-cards'
    | '/students/import'
    | '/students/reports'
    | '/timetable/substitutions'
    | '/api/public/verify'
    | '/academics'
    | '/attendance'
    | '/exams'
    | '/lms'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/academics/departments/$departmentId'
    | '/academics/programs/$programId'
    | '/settings/templates/$channel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forbidden'
    | '/maintenance'
    | '/reset-password'
    | '/unauthorized'
    | '/verify'
    | '/_authenticated/settings'
    | '/_authenticated/activity'
    | '/_authenticated/approvals'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/documents'
    | '/_authenticated/faculty'
    | '/_authenticated/media'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/programs'
    | '/_authenticated/roles'
    | '/_authenticated/staff'
    | '/_authenticated/student'
    | '/_authenticated/teaching'
    | '/_authenticated/users'
    | '/_authenticated/academics/allocations'
    | '/_authenticated/academics/analytics'
    | '/_authenticated/academics/bulk'
    | '/_authenticated/academics/calendar'
    | '/_authenticated/academics/credits'
    | '/_authenticated/academics/curriculum'
    | '/_authenticated/academics/enrollment'
    | '/_authenticated/academics/infrastructure'
    | '/_authenticated/academics/reports'
    | '/_authenticated/academics/structure'
    | '/_authenticated/academics/subjects'
    | '/_authenticated/academics/workload'
    | '/_authenticated/attendance/analytics'
    | '/_authenticated/attendance/corrections'
    | '/_authenticated/attendance/leave'
    | '/_authenticated/attendance/mark'
    | '/_authenticated/attendance/my'
    | '/_authenticated/attendance/policies'
    | '/_authenticated/attendance/reports'
    | '/_authenticated/attendance/sessions'
    | '/_authenticated/exams/analytics'
    | '/_authenticated/exams/certificates'
    | '/_authenticated/exams/evaluation'
    | '/_authenticated/exams/framework'
    | '/_authenticated/exams/hall-tickets'
    | '/_authenticated/exams/invigilation'
    | '/_authenticated/exams/marks'
    | '/_authenticated/exams/papers'
    | '/_authenticated/exams/planning'
    | '/_authenticated/exams/question-bank'
    | '/_authenticated/exams/registrations'
    | '/_authenticated/exams/reports'
    | '/_authenticated/exams/results'
    | '/_authenticated/exams/revaluation'
    | '/_authenticated/exams/seating'
    | '/_authenticated/exams/sessions'
    | '/_authenticated/lms/$workspaceId'
    | '/_authenticated/settings/$scope'
    | '/_authenticated/settings/api'
    | '/_authenticated/settings/features'
    | '/_authenticated/settings/storage'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/admissions'
    | '/_authenticated/students/id-cards'
    | '/_authenticated/students/import'
    | '/_authenticated/students/reports'
    | '/_authenticated/timetable/substitutions'
    | '/api/public/verify'
    | '/_authenticated/academics/'
    | '/_authenticated/attendance/'
    | '/_authenticated/exams/'
    | '/_authenticated/lms/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/timetable/'
    | '/_authenticated/academics/departments/$departmentId'
    | '/_authenticated/academics/programs/$programId'
    | '/_authenticated/settings/templates/$channel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForbiddenRoute: typeof ForbiddenRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicVerifyRoute: typeof ApiPublicVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty': {
      id: '/_authenticated/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AuthenticatedFacultyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programs': {
      id: '/_authenticated/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedProgramsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teaching': {
      id: '/_authenticated/teaching'
      path: '/teaching'
      fullPath: '/teaching'
      preLoaderRoute: typeof AuthenticatedTeachingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/': {
      id: '/_authenticated/academics/'
      path: '/academics'
      fullPath: '/academics/'
      preLoaderRoute: typeof AuthenticatedAcademicsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/allocations': {
      id: '/_authenticated/academics/allocations'
      path: '/academics/allocations'
      fullPath: '/academics/allocations'
      preLoaderRoute: typeof AuthenticatedAcademicsAllocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/analytics': {
      id: '/_authenticated/academics/analytics'
      path: '/academics/analytics'
      fullPath: '/academics/analytics'
      preLoaderRoute: typeof AuthenticatedAcademicsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/bulk': {
      id: '/_authenticated/academics/bulk'
      path: '/academics/bulk'
      fullPath: '/academics/bulk'
      preLoaderRoute: typeof AuthenticatedAcademicsBulkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/calendar': {
      id: '/_authenticated/academics/calendar'
      path: '/academics/calendar'
      fullPath: '/academics/calendar'
      preLoaderRoute: typeof AuthenticatedAcademicsCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/credits': {
      id: '/_authenticated/academics/credits'
      path: '/academics/credits'
      fullPath: '/academics/credits'
      preLoaderRoute: typeof AuthenticatedAcademicsCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/curriculum': {
      id: '/_authenticated/academics/curriculum'
      path: '/academics/curriculum'
      fullPath: '/academics/curriculum'
      preLoaderRoute: typeof AuthenticatedAcademicsCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/enrollment': {
      id: '/_authenticated/academics/enrollment'
      path: '/academics/enrollment'
      fullPath: '/academics/enrollment'
      preLoaderRoute: typeof AuthenticatedAcademicsEnrollmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/infrastructure': {
      id: '/_authenticated/academics/infrastructure'
      path: '/academics/infrastructure'
      fullPath: '/academics/infrastructure'
      preLoaderRoute: typeof AuthenticatedAcademicsInfrastructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/reports': {
      id: '/_authenticated/academics/reports'
      path: '/academics/reports'
      fullPath: '/academics/reports'
      preLoaderRoute: typeof AuthenticatedAcademicsReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/structure': {
      id: '/_authenticated/academics/structure'
      path: '/academics/structure'
      fullPath: '/academics/structure'
      preLoaderRoute: typeof AuthenticatedAcademicsStructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/subjects': {
      id: '/_authenticated/academics/subjects'
      path: '/academics/subjects'
      fullPath: '/academics/subjects'
      preLoaderRoute: typeof AuthenticatedAcademicsSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/workload': {
      id: '/_authenticated/academics/workload'
      path: '/academics/workload'
      fullPath: '/academics/workload'
      preLoaderRoute: typeof AuthenticatedAcademicsWorkloadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/analytics': {
      id: '/_authenticated/attendance/analytics'
      path: '/attendance/analytics'
      fullPath: '/attendance/analytics'
      preLoaderRoute: typeof AuthenticatedAttendanceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/corrections': {
      id: '/_authenticated/attendance/corrections'
      path: '/attendance/corrections'
      fullPath: '/attendance/corrections'
      preLoaderRoute: typeof AuthenticatedAttendanceCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/leave': {
      id: '/_authenticated/attendance/leave'
      path: '/attendance/leave'
      fullPath: '/attendance/leave'
      preLoaderRoute: typeof AuthenticatedAttendanceLeaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/mark': {
      id: '/_authenticated/attendance/mark'
      path: '/attendance/mark'
      fullPath: '/attendance/mark'
      preLoaderRoute: typeof AuthenticatedAttendanceMarkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/my': {
      id: '/_authenticated/attendance/my'
      path: '/attendance/my'
      fullPath: '/attendance/my'
      preLoaderRoute: typeof AuthenticatedAttendanceMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/policies': {
      id: '/_authenticated/attendance/policies'
      path: '/attendance/policies'
      fullPath: '/attendance/policies'
      preLoaderRoute: typeof AuthenticatedAttendancePoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/reports': {
      id: '/_authenticated/attendance/reports'
      path: '/attendance/reports'
      fullPath: '/attendance/reports'
      preLoaderRoute: typeof AuthenticatedAttendanceReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/sessions': {
      id: '/_authenticated/attendance/sessions'
      path: '/attendance/sessions'
      fullPath: '/attendance/sessions'
      preLoaderRoute: typeof AuthenticatedAttendanceSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/analytics': {
      id: '/_authenticated/exams/analytics'
      path: '/exams/analytics'
      fullPath: '/exams/analytics'
      preLoaderRoute: typeof AuthenticatedExamsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/certificates': {
      id: '/_authenticated/exams/certificates'
      path: '/exams/certificates'
      fullPath: '/exams/certificates'
      preLoaderRoute: typeof AuthenticatedExamsCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/evaluation': {
      id: '/_authenticated/exams/evaluation'
      path: '/exams/evaluation'
      fullPath: '/exams/evaluation'
      preLoaderRoute: typeof AuthenticatedExamsEvaluationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/framework': {
      id: '/_authenticated/exams/framework'
      path: '/exams/framework'
      fullPath: '/exams/framework'
      preLoaderRoute: typeof AuthenticatedExamsFrameworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/hall-tickets': {
      id: '/_authenticated/exams/hall-tickets'
      path: '/exams/hall-tickets'
      fullPath: '/exams/hall-tickets'
      preLoaderRoute: typeof AuthenticatedExamsHallTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/invigilation': {
      id: '/_authenticated/exams/invigilation'
      path: '/exams/invigilation'
      fullPath: '/exams/invigilation'
      preLoaderRoute: typeof AuthenticatedExamsInvigilationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/marks': {
      id: '/_authenticated/exams/marks'
      path: '/exams/marks'
      fullPath: '/exams/marks'
      preLoaderRoute: typeof AuthenticatedExamsMarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/papers': {
      id: '/_authenticated/exams/papers'
      path: '/exams/papers'
      fullPath: '/exams/papers'
      preLoaderRoute: typeof AuthenticatedExamsPapersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/planning': {
      id: '/_authenticated/exams/planning'
      path: '/exams/planning'
      fullPath: '/exams/planning'
      preLoaderRoute: typeof AuthenticatedExamsPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/question-bank': {
      id: '/_authenticated/exams/question-bank'
      path: '/exams/question-bank'
      fullPath: '/exams/question-bank'
      preLoaderRoute: typeof AuthenticatedExamsQuestionBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/registrations': {
      id: '/_authenticated/exams/registrations'
      path: '/exams/registrations'
      fullPath: '/exams/registrations'
      preLoaderRoute: typeof AuthenticatedExamsRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/reports': {
      id: '/_authenticated/exams/reports'
      path: '/exams/reports'
      fullPath: '/exams/reports'
      preLoaderRoute: typeof AuthenticatedExamsReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/results': {
      id: '/_authenticated/exams/results'
      path: '/exams/results'
      fullPath: '/exams/results'
      preLoaderRoute: typeof AuthenticatedExamsResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/revaluation': {
      id: '/_authenticated/exams/revaluation'
      path: '/exams/revaluation'
      fullPath: '/exams/revaluation'
      preLoaderRoute: typeof AuthenticatedExamsRevaluationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/seating': {
      id: '/_authenticated/exams/seating'
      path: '/exams/seating'
      fullPath: '/exams/seating'
      preLoaderRoute: typeof AuthenticatedExamsSeatingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/sessions': {
      id: '/_authenticated/exams/sessions'
      path: '/exams/sessions'
      fullPath: '/exams/sessions'
      preLoaderRoute: typeof AuthenticatedExamsSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lms/': {
      id: '/_authenticated/lms/'
      path: '/lms'
      fullPath: '/lms/'
      preLoaderRoute: typeof AuthenticatedLmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lms/$workspaceId': {
      id: '/_authenticated/lms/$workspaceId'
      path: '/lms/$workspaceId'
      fullPath: '/lms/$workspaceId'
      preLoaderRoute: typeof AuthenticatedLmsWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/$scope': {
      id: '/_authenticated/settings/$scope'
      path: '/$scope'
      fullPath: '/settings/$scope'
      preLoaderRoute: typeof AuthenticatedSettingsScopeRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api': {
      id: '/_authenticated/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthenticatedSettingsApiRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/features': {
      id: '/_authenticated/settings/features'
      path: '/features'
      fullPath: '/settings/features'
      preLoaderRoute: typeof AuthenticatedSettingsFeaturesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/storage': {
      id: '/_authenticated/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof AuthenticatedSettingsStorageRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/admissions': {
      id: '/_authenticated/students/admissions'
      path: '/students/admissions'
      fullPath: '/students/admissions'
      preLoaderRoute: typeof AuthenticatedStudentsAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/id-cards': {
      id: '/_authenticated/students/id-cards'
      path: '/students/id-cards'
      fullPath: '/students/id-cards'
      preLoaderRoute: typeof AuthenticatedStudentsIdCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/import': {
      id: '/_authenticated/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AuthenticatedStudentsImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/reports': {
      id: '/_authenticated/students/reports'
      path: '/students/reports'
      fullPath: '/students/reports'
      preLoaderRoute: typeof AuthenticatedStudentsReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/': {
      id: '/_authenticated/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof AuthenticatedTimetableIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable/substitutions': {
      id: '/_authenticated/timetable/substitutions'
      path: '/timetable/substitutions'
      fullPath: '/timetable/substitutions'
      preLoaderRoute: typeof AuthenticatedTimetableSubstitutionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/verify': {
      id: '/api/public/verify'
      path: '/api/public/verify'
      fullPath: '/api/public/verify'
      preLoaderRoute: typeof ApiPublicVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academics/departments/$departmentId': {
      id: '/_authenticated/academics/departments/$departmentId'
      path: '/academics/departments/$departmentId'
      fullPath: '/academics/departments/$departmentId'
      preLoaderRoute: typeof AuthenticatedAcademicsDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academics/programs/$programId': {
      id: '/_authenticated/academics/programs/$programId'
      path: '/academics/programs/$programId'
      fullPath: '/academics/programs/$programId'
      preLoaderRoute: typeof AuthenticatedAcademicsProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/templates/$channel': {
      id: '/_authenticated/settings/templates/$channel'
      path: '/templates/$channel'
      fullPath: '/settings/templates/$channel'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesChannelRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsScopeRoute: typeof AuthenticatedSettingsScopeRoute
  AuthenticatedSettingsApiRoute: typeof AuthenticatedSettingsApiRoute
  AuthenticatedSettingsFeaturesRoute: typeof AuthenticatedSettingsFeaturesRoute
  AuthenticatedSettingsStorageRoute: typeof AuthenticatedSettingsStorageRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsTemplatesChannelRoute: typeof AuthenticatedSettingsTemplatesChannelRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsScopeRoute: AuthenticatedSettingsScopeRoute,
    AuthenticatedSettingsApiRoute: AuthenticatedSettingsApiRoute,
    AuthenticatedSettingsFeaturesRoute: AuthenticatedSettingsFeaturesRoute,
    AuthenticatedSettingsStorageRoute: AuthenticatedSettingsStorageRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsTemplatesChannelRoute:
      AuthenticatedSettingsTemplatesChannelRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFacultyRoute: typeof AuthenticatedFacultyRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgramsRoute: typeof AuthenticatedProgramsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
  AuthenticatedTeachingRoute: typeof AuthenticatedTeachingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAcademicsAllocationsRoute: typeof AuthenticatedAcademicsAllocationsRoute
  AuthenticatedAcademicsAnalyticsRoute: typeof AuthenticatedAcademicsAnalyticsRoute
  AuthenticatedAcademicsBulkRoute: typeof AuthenticatedAcademicsBulkRoute
  AuthenticatedAcademicsCalendarRoute: typeof AuthenticatedAcademicsCalendarRoute
  AuthenticatedAcademicsCreditsRoute: typeof AuthenticatedAcademicsCreditsRoute
  AuthenticatedAcademicsCurriculumRoute: typeof AuthenticatedAcademicsCurriculumRoute
  AuthenticatedAcademicsEnrollmentRoute: typeof AuthenticatedAcademicsEnrollmentRoute
  AuthenticatedAcademicsInfrastructureRoute: typeof AuthenticatedAcademicsInfrastructureRoute
  AuthenticatedAcademicsReportsRoute: typeof AuthenticatedAcademicsReportsRoute
  AuthenticatedAcademicsStructureRoute: typeof AuthenticatedAcademicsStructureRoute
  AuthenticatedAcademicsSubjectsRoute: typeof AuthenticatedAcademicsSubjectsRoute
  AuthenticatedAcademicsWorkloadRoute: typeof AuthenticatedAcademicsWorkloadRoute
  AuthenticatedAttendanceAnalyticsRoute: typeof AuthenticatedAttendanceAnalyticsRoute
  AuthenticatedAttendanceCorrectionsRoute: typeof AuthenticatedAttendanceCorrectionsRoute
  AuthenticatedAttendanceLeaveRoute: typeof AuthenticatedAttendanceLeaveRoute
  AuthenticatedAttendanceMarkRoute: typeof AuthenticatedAttendanceMarkRoute
  AuthenticatedAttendanceMyRoute: typeof AuthenticatedAttendanceMyRoute
  AuthenticatedAttendancePoliciesRoute: typeof AuthenticatedAttendancePoliciesRoute
  AuthenticatedAttendanceReportsRoute: typeof AuthenticatedAttendanceReportsRoute
  AuthenticatedAttendanceSessionsRoute: typeof AuthenticatedAttendanceSessionsRoute
  AuthenticatedExamsAnalyticsRoute: typeof AuthenticatedExamsAnalyticsRoute
  AuthenticatedExamsCertificatesRoute: typeof AuthenticatedExamsCertificatesRoute
  AuthenticatedExamsEvaluationRoute: typeof AuthenticatedExamsEvaluationRoute
  AuthenticatedExamsFrameworkRoute: typeof AuthenticatedExamsFrameworkRoute
  AuthenticatedExamsHallTicketsRoute: typeof AuthenticatedExamsHallTicketsRoute
  AuthenticatedExamsInvigilationRoute: typeof AuthenticatedExamsInvigilationRoute
  AuthenticatedExamsMarksRoute: typeof AuthenticatedExamsMarksRoute
  AuthenticatedExamsPapersRoute: typeof AuthenticatedExamsPapersRoute
  AuthenticatedExamsPlanningRoute: typeof AuthenticatedExamsPlanningRoute
  AuthenticatedExamsQuestionBankRoute: typeof AuthenticatedExamsQuestionBankRoute
  AuthenticatedExamsRegistrationsRoute: typeof AuthenticatedExamsRegistrationsRoute
  AuthenticatedExamsReportsRoute: typeof AuthenticatedExamsReportsRoute
  AuthenticatedExamsResultsRoute: typeof AuthenticatedExamsResultsRoute
  AuthenticatedExamsRevaluationRoute: typeof AuthenticatedExamsRevaluationRoute
  AuthenticatedExamsSeatingRoute: typeof AuthenticatedExamsSeatingRoute
  AuthenticatedExamsSessionsRoute: typeof AuthenticatedExamsSessionsRoute
  AuthenticatedLmsWorkspaceIdRoute: typeof AuthenticatedLmsWorkspaceIdRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsAdmissionsRoute: typeof AuthenticatedStudentsAdmissionsRoute
  AuthenticatedStudentsIdCardsRoute: typeof AuthenticatedStudentsIdCardsRoute
  AuthenticatedStudentsImportRoute: typeof AuthenticatedStudentsImportRoute
  AuthenticatedStudentsReportsRoute: typeof AuthenticatedStudentsReportsRoute
  AuthenticatedTimetableSubstitutionsRoute: typeof AuthenticatedTimetableSubstitutionsRoute
  AuthenticatedAcademicsIndexRoute: typeof AuthenticatedAcademicsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedLmsIndexRoute: typeof AuthenticatedLmsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTimetableIndexRoute: typeof AuthenticatedTimetableIndexRoute
  AuthenticatedAcademicsDepartmentsDepartmentIdRoute: typeof AuthenticatedAcademicsDepartmentsDepartmentIdRoute
  AuthenticatedAcademicsProgramsProgramIdRoute: typeof AuthenticatedAcademicsProgramsProgramIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFacultyRoute: AuthenticatedFacultyRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgramsRoute: AuthenticatedProgramsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
  AuthenticatedTeachingRoute: AuthenticatedTeachingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAcademicsAllocationsRoute:
    AuthenticatedAcademicsAllocationsRoute,
  AuthenticatedAcademicsAnalyticsRoute: AuthenticatedAcademicsAnalyticsRoute,
  AuthenticatedAcademicsBulkRoute: AuthenticatedAcademicsBulkRoute,
  AuthenticatedAcademicsCalendarRoute: AuthenticatedAcademicsCalendarRoute,
  AuthenticatedAcademicsCreditsRoute: AuthenticatedAcademicsCreditsRoute,
  AuthenticatedAcademicsCurriculumRoute: AuthenticatedAcademicsCurriculumRoute,
  AuthenticatedAcademicsEnrollmentRoute: AuthenticatedAcademicsEnrollmentRoute,
  AuthenticatedAcademicsInfrastructureRoute:
    AuthenticatedAcademicsInfrastructureRoute,
  AuthenticatedAcademicsReportsRoute: AuthenticatedAcademicsReportsRoute,
  AuthenticatedAcademicsStructureRoute: AuthenticatedAcademicsStructureRoute,
  AuthenticatedAcademicsSubjectsRoute: AuthenticatedAcademicsSubjectsRoute,
  AuthenticatedAcademicsWorkloadRoute: AuthenticatedAcademicsWorkloadRoute,
  AuthenticatedAttendanceAnalyticsRoute: AuthenticatedAttendanceAnalyticsRoute,
  AuthenticatedAttendanceCorrectionsRoute:
    AuthenticatedAttendanceCorrectionsRoute,
  AuthenticatedAttendanceLeaveRoute: AuthenticatedAttendanceLeaveRoute,
  AuthenticatedAttendanceMarkRoute: AuthenticatedAttendanceMarkRoute,
  AuthenticatedAttendanceMyRoute: AuthenticatedAttendanceMyRoute,
  AuthenticatedAttendancePoliciesRoute: AuthenticatedAttendancePoliciesRoute,
  AuthenticatedAttendanceReportsRoute: AuthenticatedAttendanceReportsRoute,
  AuthenticatedAttendanceSessionsRoute: AuthenticatedAttendanceSessionsRoute,
  AuthenticatedExamsAnalyticsRoute: AuthenticatedExamsAnalyticsRoute,
  AuthenticatedExamsCertificatesRoute: AuthenticatedExamsCertificatesRoute,
  AuthenticatedExamsEvaluationRoute: AuthenticatedExamsEvaluationRoute,
  AuthenticatedExamsFrameworkRoute: AuthenticatedExamsFrameworkRoute,
  AuthenticatedExamsHallTicketsRoute: AuthenticatedExamsHallTicketsRoute,
  AuthenticatedExamsInvigilationRoute: AuthenticatedExamsInvigilationRoute,
  AuthenticatedExamsMarksRoute: AuthenticatedExamsMarksRoute,
  AuthenticatedExamsPapersRoute: AuthenticatedExamsPapersRoute,
  AuthenticatedExamsPlanningRoute: AuthenticatedExamsPlanningRoute,
  AuthenticatedExamsQuestionBankRoute: AuthenticatedExamsQuestionBankRoute,
  AuthenticatedExamsRegistrationsRoute: AuthenticatedExamsRegistrationsRoute,
  AuthenticatedExamsReportsRoute: AuthenticatedExamsReportsRoute,
  AuthenticatedExamsResultsRoute: AuthenticatedExamsResultsRoute,
  AuthenticatedExamsRevaluationRoute: AuthenticatedExamsRevaluationRoute,
  AuthenticatedExamsSeatingRoute: AuthenticatedExamsSeatingRoute,
  AuthenticatedExamsSessionsRoute: AuthenticatedExamsSessionsRoute,
  AuthenticatedLmsWorkspaceIdRoute: AuthenticatedLmsWorkspaceIdRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsAdmissionsRoute: AuthenticatedStudentsAdmissionsRoute,
  AuthenticatedStudentsIdCardsRoute: AuthenticatedStudentsIdCardsRoute,
  AuthenticatedStudentsImportRoute: AuthenticatedStudentsImportRoute,
  AuthenticatedStudentsReportsRoute: AuthenticatedStudentsReportsRoute,
  AuthenticatedTimetableSubstitutionsRoute:
    AuthenticatedTimetableSubstitutionsRoute,
  AuthenticatedAcademicsIndexRoute: AuthenticatedAcademicsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedLmsIndexRoute: AuthenticatedLmsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTimetableIndexRoute: AuthenticatedTimetableIndexRoute,
  AuthenticatedAcademicsDepartmentsDepartmentIdRoute:
    AuthenticatedAcademicsDepartmentsDepartmentIdRoute,
  AuthenticatedAcademicsProgramsProgramIdRoute:
    AuthenticatedAcademicsProgramsProgramIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForbiddenRoute: ForbiddenRoute,
  MaintenanceRoute: MaintenanceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicVerifyRoute: ApiPublicVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
